Вычисление факториала
js-tasks-ru/jsbasic-20220901_trytobeuseful pull request #2
Opened 2022-09-06 18:12 UTC by GestaltKir

2022-09-06 18:13 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-07 11:45 UTC, SinimaWath requested changes

2022-09-07 11:45 UTC, SinimaWath commented on 1-module/1-task/index.js
> +    result = 1;
Тут должен быть let - перед обявлением переменной

2022-09-08 15:30 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-08 15:32 UTC, GestaltKir commented on 1-module/1-task/index.js
> +    result = 1;
Исправил. Немного намудрил с коммитами, прошу прощения

2022-09-09 10:15 UTC, SinimaWath requested changes

2022-09-09 10:15 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  if (upStr.includes('XXX') || upStr.includes('1XBET')){
`upStr.includes('XXX') || upStr.includes('1XBET')` - и так результат boolean, поэтому if тут не нужен:
`return upStr.includes('XXX') || upStr.includes('1XBET')`

2022-09-09 10:15 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  else return str
1 - else тут лишний
2 - временная переменаня strLen тоже лишняя:
```
if (str.length > maxlength) {
  return ...;
}

return str;
```

2022-09-11 11:36 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-11 15:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-12 19:11 UTC, SinimaWath approved these changes

2022-09-12 19:12 UTC, merged