Решение 3 модуля
js-tasks-ru/jsbasic-20220901_trytobeuseful pull request #3
Opened 2022-09-15 17:27 UTC by GestaltKir

2022-09-15 17:27 UTC, GestaltKir commented
5 задачу еще джолжен

2022-09-15 17:27 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-16 17:04 UTC, SinimaWath requested changes

2022-09-16 17:04 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return names
давай переделаем на метод mao

2022-09-16 17:04 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  return result
давай переделаем на:
```
return arr.filter(...).map(...)
```

2022-09-16 17:04 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return camelWords.join('')
давай попробуем:
```
return str.split('-').map((value, index) => {}).join('')
```

2022-09-16 17:04 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return names.join('\n');
тут можно проще:
```
return users.filter(..).map(...).join(...)
```

2022-09-17 10:49 UTC, GestaltKir commented on 3-module/3-task/index.js
> +  return camelWords.join('')
У меня получается сделать только так: 
`function camelize(str) {
  return str.split('-').map((value, index) => {
    value[0].toUpperCase()+value.substr(1)
  }).join('')
}`

Но это не работает, и я не могу понять почему.

2022-09-17 11:22 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-17 19:00 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return camelWords.join('')
потому что по условию задачи, не надо делять toUpperCase для 1 елемента

2022-09-18 07:04 UTC, GestaltKir commented on 3-module/3-task/index.js
> +  return camelWords.join('')
Я понимаю, но метод у меня вообще ничего не возвращает

2022-09-19 11:21 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return camelWords.join('')
Не хватает return:

`function camelize(str) { return str.split('-').map((value, index) => { return value[0].toUpperCase()+value.substr(1) }).join('') }`

Либо надо убрать фигурные скобки

`function camelize(str) { return str.split('-').map((value, index) => value[0].toUpperCase()+value.substr(1) }).join('')`

2022-09-19 18:44 UTC, GestaltKir commented on 3-module/3-task/index.js
> +  return camelWords.join('')
Исправил. Прошу прощения за такую глупость

2022-09-19 18:45 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-19 21:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-23 12:57 UTC, SinimaWath approved these changes

2022-09-23 12:58 UTC, merged